baseURL = "https://nerddis.co/"
languageCode = "en-us"
title = "NERDDISCO"
theme = "landing-page"

[params]
  description = """digital artist, 
    <a href="https://github.com/TimPietrusky">open source hacker</a>, 
    co-founder of <a href="https://livejs.network">LiveJS</a>, 
    1/2 of <a href="https://schickmalzwo.de">schickmalzwo</a>,
    <a href="https://visualandlightworkshop.com">mentor</a>,
    <a href="https://github.com/NERDDISCO">visual spectacular</a>,
    <a href="https://github.com/NERDDISCO/luminave">lightweaver</a> 
    and loop-drop-rookie"""
  
  isLive = false
  liveText = '<span class="live">LIVE</span> on <a href="https://twitch.com/NERDDISCO">Twitch</a> at 21:00 CEST'
  liveTitle = 'üî¥ LIVE on Twitch at 21:00 CEST'

[[params.social]]
  title = "youtube"
  icon = "youtube"
  url = "https://www.youtube.com/channel/UCjEh7ggQuxsI3JjqRUJfeAQ"
[[params.social]]
  title = "twitch"
  icon = "twitch"
  url = "https://www.twitch.com/nerddisco"
[[params.social]]
  title = "twitter"
  icon = "twitter"
  url = "https://www.twitter.com/NERDDISCO"
[[params.social]]
  title = "instagram"
  icon = "instagram"
  url = "https://www.instagram.com/TimPietrusky"
[[params.social]]
  title = "facebook"
  icon = "facebook"
  url = "https://facebook.com/TimPietrusky"
[[params.social]]
  title = "github"
  icon = "github"
  url = "https://github.com/NERDDISCO/nerddis.co"






[[params.next]]
  date = "2020/09/17 - 21:00 CEST"
  title = "half/byte & NERDDISCO - STXBP1"
  url = "https://www.twitch.tv/nerddisco"





[[params.shows]]
  date = "2020/09/12"
  title = "2xAA & NERDDISCO @ Open UP Summit 2020"
  img = "20200912_2xAA_NERDDISCO_OpenUpSummit_2020"
  url = "https://youtu.be/RhM3arvVAPM"
  length = "00:14:39"
  # [[params.next]]
#   date = "2020/09/12 - 16:30 CEST"
#   title = "Sam Wray & Tim Pietrusky - Creating An Audio/Visual Performance Using The Web @ Open Up Summit 2020"
#   url = "https://www.openup.global"
[[params.shows]]
  date = "2020/08/21"
  title = "half/byte & NERDDISCO @ #NoRuKo 2020"
  img = "20200821_halfbyte_NERDDISCO_NoRuKo"
  url = "https://youtu.be/XntC412ETgM"
  length = "00:29:51"
[[params.shows]]
  date = "2020/08/17"
  title = "NERDDISCO - Diamond Shader Test"
  img = "20200817_NERDDISCO_Diamond_Shader_Test"
  url = "https://youtu.be/HSelmP6ugCY"
  length = "00:03:56"
[[params.shows]]
  date = "2020/08/13"
  title = "half/byte & NERDDISCO - Sommerloch"
  img = "20200813_halfbyte_NERDDISCO_Sommerloch"
  url = "https://youtu.be/V_CphjFIDxw"
  length = "01:00:20"
[[params.shows]]
  date = "2020/07/09"
  title = "half/byte & NERDDISCO - Kohleausstieg"
  img = "20200709_halfbyte_NERDDISCO_Kohleausstieg"
  url = "https://youtu.be/iExiOmnNb6o"
  length = "01:00:31"
[[params.shows]]
  date = "2020/06/04"
  title = "half/byte & NERDDISCO - #BLM"
  img = "20200604_halfbyte_NERDDISCO_BLM"
  url = "https://youtu.be/c8k45Q0PL8I"
  length = "01:31:05"
[[params.shows]]
  date = "2020/05/30"
  title = "Stonecreek Crew & NERDDISCO - 'Urban Bass Bungle Donation Stream' in collaboration with Banana Bass Music"
  img = "20200530_StonecreekCrew_NERDDISCO_Urban_Bass_Bungle_Donation_Stream"
  url = "https://youtu.be/ZFm9ht6cgBI?t=20"
  length = "03:47:40"
[[params.shows]]
  date = "2020/05/09"
  title = "2xAA & DESTROY WITH SCIENCE & Kellective & half/byte & NERDDISCO & NO_SIGNAL - 1. LiveJS / feedhack jam"
  img = "20200509_LiveJS_using_feedhack"
  url = "https://www.pscp.tv/w/1YqKDEeXpBQGV#"
  length = "02:17:29"
[[params.shows]]
  date = "2020/05/03"
  title = "_ok_bai & NERDDISCO - dreamscape"
  img = "20200503_ok_bai_NERDDISCO_dreamscape"
  url = "https://youtu.be/-ihAED403u4"
  length = "00:52"
[[params.shows]]
  date = "2020/04/11"
  title = "HOSTILE & NERDDISCO @ Ausgangssperre 2, Peng"
  img = "20200411_HOSTILE_NERDDISCO_Ausgangssperre_2_Peng"
  url = "https://youtu.be/udnJNQtjKwU"
  length = "30:13"
[[params.shows]]
  date = "2020/04/11"
  title = "Haniman & NERDDISCO @ Ausgangssperre 2, Peng"
  img = "20200411_Haniman_NERDDISCO_Ausgangssperre_2_Peng"
  url = "https://youtu.be/Kq0RVN5xT1A"
  length = "01:54:25"
[[params.shows]]
  date = "2020/04/11"
  title = "half/byte & NERDDISCO @ Ausgangssperre 2, Peng"
  img = "20200411_halfbyte_NERDDISCO_Ausgangssperre_2_Peng"
  url = "https://youtu.be/8v99P5p4wX4"
  length = "48:20"
[[params.shows]]
  date = "2020/04/11"
  title = "NERDDISCO feat. V/A @ Ausgangssperre 2 - Peng, Twitch"
  img = "20200411_NERDDISCO_Ausgangssperre_2_Peng"
  url = "https://www.youtube.com/watch?v=HTp15l7k_0A"
  length = "06:34:18"
[[params.shows]]
  date = "2020/03/26"
  title = "half/byte & NERDDISCO - Stay at home!!!"
  img = "20200326_halfbyte_NERDDISCO_Stay_At_Home"
  url = "https://youtu.be/t_BXjpLXBH4"
  length = "11:00"
[[params.shows]]
  date = "2020/03/21"
  title = "NERDDISCO feat. V/A @ Ausgangssperre - Peng, Twitch"
  img = "20200321_NERDDISCO_Ausgangssperre_Peng"
  url = "https://www.youtube.com/watch?v=ylagilIkzj0"
  length = "07:28:54"
[[params.shows]]
  date = "2020/03/12"
  title = "half/byte & NERDDISCO - Lesson 2"
  img = "20200312_halfbyte_NERDDISCO_Lesson_2"
  url = "https://youtu.be/Qh0GymCwKa8"  
  length = "01:08:17"
[[params.shows]]
  date = "2020/02/21"
  title = "schickmalzwo @ Hybris - Peng, Mainz, Germany"
  img = "20200221_schickmalzwo_Hybris_Peng"
  url = "https://youtu.be/0-mclBorQwo"
  length = "00:14"
[[params.shows]]
  date = "2020/01/09"
  title = "half/byte & NERDDISCO - Lesson 1"
  img = "20200109_halfbyte_NERDDISCO_Lesson_1"
  url = "https://youtu.be/rRf5tVPkqLY"
  length = "01:59:30"
[[params.shows]]
  date = "2019/06/15"
  title = "LiveJS - half/byte & NERDDISCO with Olivia Jack @ JSConf Asia - LASALLE College of the Arts, Singapore"
  img = "20190615_halfbyte_Olivia_Jack_NERDDISCO_JSConfAsia"
  url = "https://youtu.be/IjuICGSpV0M"
  length = "14:26"
[[params.shows]]
  date = "2019/06/15"
  title = "LiveJS - DESTROY WITH SCIENCE & NERDDISCO @ JSConf Asia - LASALLE College of the Arts, Singapore"
  img = "20190615_DESTROY_WITH_SCIENCE_NERDDISCO_JSConfAsia"
  url = "https://youtu.be/yMbfu5QiS7c"
  length = "24:59"
[[params.shows]]
  date = "2019/06/02"
  title = "LiveJS - Making of this.stage @ JSConf EU Festival X - Arena Berlin, Berlin, Germany"
  img = "20190601_LiveJS_Making_of_this_stage_JSConfEU_Festival_X"
  url = "https://www.youtube.com/watch?v=jae837XA82Q"
  length = "32:13"
[[params.shows]]
  date = "2019/06/01"
  title = "LiveJS @ JSConf EU Festival X Opening - Arena Berlin, Berlin, Germany"
  img = "20190601_LiveJS_JSConfEU_Festival_X_Opening"
  url = "https://www.youtube.com/watch?v=o1rzsna263c"
  length = "25:36"
[[params.shows]]
  date = "2019/03/17"
  title = "schickmalzwo @ Jasmin's birthday bash - DAS DORF, Mainz, Germany"
  img = "20190317_schickmalzwo_Jasmins_birthday_bash_DASDORF"
  url = "https://youtu.be/RsqeSfyhzdw"
  length = "09:48"
[[params.shows]]
  date = "2019/02/03"
  title = "oltoko & NERDDISCO - All the Lights @ Tim's Castle, H√∂chst im Odenwald, Germany"
  img = "20190203_oltoko_NERDDISCO_All_the_Lights"
  url = "https://www.youtube.com/watch?v=Qq9V5KHAf0s"
  length = "05:45"
[[params.shows]]
  date = "2018/12/24"
  title = "HOSTILE & NERDDISCO - HOSTILE PODCAST 003"
  img = "20181224_HOSTILE_NERDDISCO_HOSTILE_PODCAST_003"
  url = "https://www.youtube.com/watch?v=GzuHPz4wUEM"
  length = "29:20"
[[params.shows]]
  date = "2018/11/09"
  title = "LiveJS - 2xAA & half/byte & NERDDISCO @ dotJS Afterparty - Dock Pullman, Paris, France"
  img = "20181109_2xAA_halfbyte_NERDDISCO_dotJS_Afterparty"
  url = "https://www.youtube.com/watch?v=79eYdK9G8rU"  
  length = "01:23:38"
[[params.shows]]
  date = "2018/11/09"
  title = "Tim Pietrusky - WebUSB for Digital Artists @ dotJS - Dock Pullman, Paris, France"
  img = "20181109_Tim_Pietrusky_WebUSB_for_Digital_Artists_dotJS"
  url = "https://www.dotconferences.com/2018/11/tim-pietrusky-webusb-for-digital-artists"
  length = "04:20"
[[params.shows]]
  date = "2018/10/13"
  title = "LiveJS - 2xAA & half/byte & NERDDISCO & usefulthink @ RuhrJS Afterparty - Rotunde, Bochum, Germany"
  img = "20181013_2xAA_halfbyte_NERDDISCO_usefulthink_RuhrJS_Afterparty"
  url = "https://youtu.be/U9NziTXy1S4"
  length = "40:01"
[[params.shows]]
  date = "2018/10/13"
  title = "Jan Krutisch & Martin Schuhfuss & Sam Wray & Tim Pietrusky - How does a LiveJS show work? @ RuhrJS - Rotunde, Bochum, Germany"
  img = "20181013_Jan_Krutisch_Martin_Schuhfuss_Sam_Wray_Tim_Pietrusky_RuhrJS"
  url = "https://youtu.be/C7uSKKnT3WA"
  length = "14:59"
[[params.shows]]
  date = "2018/10/13"
  title = "LiveJS - 2xAA & half/byte & NERDDISCO @ RuhrJS Opening - Rotunde, Bochum, Germany"
  img = "20181013_2xAA_halfbyte_NERDDISCO_RuhrJS_Opening"
  url = "https://youtu.be/CqPO6b6UYcg"
  length = "09:20"
[[params.shows]]
  date = "2018/06/02"
  title = "LiveJS @ JSConfEU Opening - Arena Berlin, Berlin, Germany"
  img = "20180602_LiveJS_JSConfEU_Opening"
  url = "https://youtu.be/dPWRaN2PXZw?t=158"
  length = "04:14"
[[params.shows]]
  date = "2017/05/07"
  title = "LiveJS - 2xAA & DESTROY WITH SCIENCE & half/byte & NERDDISCO & rumyra & usefulthink with NESTED LOOPS - People Got Mad JavaScript @ JSConfEU - Arena Berlin, Berlin, Germany"
  img = "20170507_LiveJS_NESTED_LOOPS_JSConfEU"
  url = "https://www.youtube.com/watch?v=a0Bt7bK6nSA"
  length = "14:52"
[[params.shows]]
  date = "2017/05/06"
  title = "LiveJS - 2xAA & DESTROY WITH SCIENCE & NERDDISCO @ JSConfEU - Arena Berlin, Berlin, Germany"
  img = "20170506_LiveJS_2xAA_DESTROY_WITH_SCIENCE_NERDDISCO_JSConfEU"
  url = "https://www.youtube.com/watch?v=RWBQ69nicmw"
  length = "53:39"
[[params.shows]]
  date = "2017/06/25"
  title = "NERDDISCO fan art - 'Soulpride & E.Decay - For The Masses (Part 2)' @ Tim's Castle, H√∂chst im Odenwald, Germany"
  img = "20170625_Soulpride_Edecay_For_The_Masses_Part2_NERDDISCO_Visuals"
  url = "https://www.youtube.com/watch?v=lhZNsHjug4Y"
  length = "05:31"
[[params.shows]]
  date = "2016/12/05"
  title = "LiveJS - 2xAA & NERDDISCO @ dotJS Afterparty - Dock Pullman, Paris, France"
  img = "20161205_2xAA_NERDDISCO_LiveJS_dotJS_Afterparty"
  url = "https://www.youtube.com/watch?v=oR9vIXlu714"
  length = "53:27"
[[params.shows]]
  date = "2016/12/05"
  title = "Sam Wray & Tim Pietrusky - {Live:JS} @ dotJS - Dock Pullman, Paris, France"
  img = "20161205_Sam_Wray_Tim_Pietrusky_LiveJS_dotJS"
  url = "https://www.youtube.com/watch?v=GA7-OfYSzvA"
  length = "18:20"
[[params.shows]]
  date = "2016/08/24"
  title = "2xAA & NERDDISCO - scream4me"
  img = "20160824_2xAA_NERDDISCO_scream4me"
  url = "https://www.youtube.com/watch?v=BuO0SBZgnvI"
  length = "02:56"
[[params.shows]]
  date = "2016/06/02"
  title = "Ruth John & Tim Pietrusky - Live audio and visual spectacular @ ScotlandJS - Dynamic Earth, Edinburgh, Scotland"
  img = "20160602_ScotlandJS_Ruth_John_Tim_Pietrusky"
  url = "https://www.youtube.com/watch?v=u0POJ1sSNAc"
  length = "26:34"
[[params.shows]]
  date = "2016/05/26"
  title = "Tim Pietrusky - I ‚ù§ Music & the Web @ EmpireJS - National Museum of the American Indian, New York, USA"
  img = "20160526_Tim_Pietrusky_I_Love_Music_and_the_Web_EmpireJS"
  url = "https://www.youtube.com/watch?v=UpOV5l14jM0"
  length = "31:35"
[[params.shows]]
  date = "2016/05/12"
  title = "Martin Schuhfuss & Tim Pietrusky - We ‚ù§ Music & the Web @ JSConf Budapest - Akv√°rium Klub, Budapest, Hungary"
  img = "20160512_Martin_Schuhfuss_Tim_Pietrusky_We_Love_Music_and_the_Web_JSConf_Budapest"
  url = "https://www.youtube.com/watch?v=KkV4alDBVhk"
  length = "33:57"
[[params.shows]]
  date = "2015/10/17"
  title = "Tim Pietrusky - NERDDISCO: Reloaded @ JSConf Colombia - Ruta N, Medell√≠n, Colombia"
  img = "20151017_Tim_Pietrusky_NERDDISCO_Reloaded_JSConf_Colombia"
  url = "https://www.youtube.com/watch?v=NhJPEAR4fbI"
  length = "26:39"
[[params.shows]]
  date = "2015/06/10"
  title = "NERDDISCO @ KarlsruheJS - ETECTURE, Karlsruhe, Germany"
  img = "20150610_NERDDISCO_KarlsruheJS"
  url = "https://www.youtube.com/watch?v=1Ia4K_luzos"
  length = "01:00"
[[params.shows]]
  date = "2015/05/06"
  title = "Tim Pietrusky - NERDDISCO: The Next Generation @ Front Trends - Centrum Artystyczne Fabryka Trzciny, Warsaw, Poland"
  img = "20150506_Tim_Pietrusky_NERDDISCO_The_Next_Generation_Front_Trends"
  url = "https://www.youtube.com/watch?v=PGHgZT2aI8o"
  length = "23:47"
[[params.shows]]
  date = "2014/09/13"
  title = "Tim Pietrusky - NERDDISCO @ JSConfEU - Radialsystem, Berlin, Germany"
  img = "20140913_NERDDISCO_JSConfEU_Berlin"
  url = "https://www.youtube.com/watch?v=tia6iP85Zuk"
  length = "26:37"
